#单机搭建
##端口9000
#spring:
#  application:
#    name: eureka-server
#server:
#  port: 9000 #端口
##配置eureka server
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false #是否将自己注册到注册中心
#    fetch-registry: false #是否从eureka中获取注册信息
#    service-url: #配置暴露给Eureka Client的请求地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#-----集群部署-------
#模拟两个EurekaServer
#端口9000 , 8000
#两个server需要相互注册
spring:
  application:
    name: eureka-server
---
#单机eureka server9000 的配置信息
spring:
  profiles: eureka
server:
  port: 9000 #端口
#配置eureka server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到注册中心
    fetch-registry: false #是否从eureka中获取注册信息
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除时间间隔,单位:毫秒
---
#执行eureka1 server9000 的配置信息
spring:
  profiles: eureka1
server:
  port: 9000 #端口
#配置eureka server
eureka:
  client:
    #register-with-eureka: false #是否将自己注册到注册中心 默认true
    #fetch-registry: false #是否从eureka中获取注册信息 默认true
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://127.0.0.1:8000/eureka/
---
#执行eureka2 server8000 的配置信息
spring:
  profiles: eureka2
server:
  port: 8000 #端口
#配置eureka server
eureka:
  client:
    #register-with-eureka: false #是否将自己注册到注册中心 默认true
    #fetch-registry: false #是否从eureka中获取注册信息 默认true
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://127.0.0.1:9000/eureka/