server:
  port: 7001 #服务端口
spring:
  application:
    name: stream_producer #指定服务名
  rabbitmq: #中间服务信息
    addresses: 192.168.126.99
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output: #内置的获取消息的通道 , 这个通道会从 hzp-default中获取消息
          destination: hzp-default  #指定消息发送的目的地,在rabbitmq中,发送到一个hzp-default的exchange中
          contentType: text/plain
        myOutput:
          destination: hzp-custom-output
          producer:
            partition-key-expression: payload  #分区关键字   对象中的id,对象
            partition-count: 2  #分区大小
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit