#网关限流测试
server:
  port: 8081 #端口
spring:
  application:
    name: api-gateway-server #服务名称
  redis:
    host: 192.168.126.99
    pool: 6379
    database: 0
  cloud: #配置SpringCloudGateway的路由
    gateway:
      routes:
      - id: product-service
        #uri: http://127.0.0.1:9001
        uri: lb://service-product #lb:// 表示去注册中心中获取服务名对应的地址
        predicates:
          #- Path=/product/**
          #想要到达url中显示服务标识/product-service 的改造
          - Path=/product-service/**
        filters:
#        - name: RequestRateLimiter
#          args:
#            # 使用SpEL从容器中获取对象
#            #key-resolver: '#{@pathKeyResolver}'
#            key-resolver: '#{@userKeyResolver}'
#            # 令牌桶每秒填充平均速率
#            redis-rate-limiter.replenishRate: 1
#            # 令牌桶的上限
#            redis-rate-limiter.burstCapacity: 3
        - RewritePath=/product-service/(?<segment>.*), /$\{segment}

# RequestRateLimiter : 使用限流过滤器,是springcloud gateway提供的
# 参数  replenishRate : 向令牌桶中填充的速率
#     burstCapacity :令牌桶的容量

#eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

---
spring:
  profiles: gateway01
  #网关限流测试
server:
  port: 8080 #端口
---
spring:
  profiles: gateway02
  #网关限流测试
server:
  port: 8081 #端口